---
title: "Stats 155 Final Project"
author: "Inbal Armony"
date: "2024-02-15"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyr)
library(tidyverse)
library(dplyr)
library(ggplot2)
library(stringr)
library(ggmap)
```

# Loading the data
```{r}
Water_Data <- read_tsv('/Users/seamusmcmurrer/Library/CloudStorage/OneDrive-Personal/Documents/College/Year 3/Spring/Stats/Stats-155-Final-Project/37217-0001-Data.tsv')

Water_Data <- read_tsv('/Users/inbalarmony/Documents/GitHub/Stats-155-Final-Project/37217-0001-Data.tsv')

# Water_Data <- read_tsv('/Users/bengr/OneDrive/Documents/GitHub/Stats-155-Final-Project')

# Water_Data <- read_tsv('https://github.com/SeamusMcM/Stats-155-Final-Project/blob/e24710482babfe81c78ae92cb6dea75a6bde35dc/37217-0001-Data.tsv')
```

# Exploring  + cleaning the data
```{r}
head(Water_Data)

Water_Data_New <- Water_Data %>% 
  # changing not detected to 0!
  mutate(TOTAL_TESTED_PFAS_PPT = ifelse(TOTAL_TESTED_PFAS_PPT == 'ND', 0,TOTAL_TESTED_PFAS_PPT)) %>% 
  mutate(PFOA_PFOS_PPT = ifelse(PFOA_PFOS_PPT == 'ND', 0,PFOA_PFOS_PPT)) %>% 
  mutate(TOTAL_TESTED_PFAS_PPT = str_replace(TOTAL_TESTED_PFAS_PPT, ",","")) %>%
  mutate(TOTAL_TESTED_PFAS_PPT = as.numeric(TOTAL_TESTED_PFAS_PPT)) 
  
  
Water_Data_New %>%  summarize(mean(TOTAL_TESTED_PFAS_PPT))


# New data set with just the top 10 counties (based off of number of test sites) 
Top10 <- Water_Data_New %>% 
  group_by(COUNTY) %>% 
  summarize(num_sites = n()) %>% 
  arrange(desc(num_sites)) %>% 
  head(10) %>% 
  left_join(Water_Data_New) %>% 
  mutate(PFAS_YES=ifelse(TOTAL_TESTED_PFAS_PPT>0, TRUE, FALSE))
```


```{r PFAS}
#numerical summaries baby!
Top10 %>%
  summarise(mean = mean(TOTAL_TESTED_PFAS_PPT),
            sd = sd(TOTAL_TESTED_PFAS_PPT),
            median = median(TOTAL_TESTED_PFAS_PPT),
            max = max(TOTAL_TESTED_PFAS_PPT))
Top10 %>%
  summarise(mean = mean(POPULATION_SERVED),
            sd = sd(POPULATION_SERVED),
            median = median(POPULATION_SERVED),
            max = max(POPULATION_SERVED))
# NOT GOOD
Top10 %>%
# one in oakland is "_" I think that 46% is raw and 53% is treated
  summarise(prop = prop.table(table(RAW_OR_TREATED)))

# GOOD
Top10 %>%
  group_by(RAW_OR_TREATED) %>%
  tally()

Top10%>%
  group_by(COUNTY) %>%
  tally() %>%
  mutate(proportion = n / sum(n)) %>%
  arrange(desc(proportion))


```


```{r plots}

Top10 %>% 
  ggplot(aes(x=COUNTY, y=TOTAL_TESTED_PFAS_PPT)) +
  geom_boxplot() +
  labs(title="PFAS Levels in Ten Most Tested Michigan Counties", y="PFAS in Tested Water (ppt)", x="County")

Top10 %>% 
  filter(TOTAL_TESTED_PFAS_PPT > 0) %>%
  ggplot(aes(y=TOTAL_TESTED_PFAS_PPT)) +
  geom_boxplot() +
  labs(title="PFAS Levels in Ten Most Tested Michigan Counties", y="PFAS in Tested Water (ppt)", x="County") +
  facet_wrap(~COUNTY, scales = "free")


Top10 %>% 
  filter(!COUNTY == "KALAMAZOO") %>% 
  ggplot(aes(x=COUNTY, y=TOTAL_TESTED_PFAS_PPT)) +
  geom_boxplot() +
  labs(title="PFAS Levels in Ten Most Tested Michigan Counties", subtitle="Exluding the County with the most PFAS, Kalamazoo", y="PFAS in Tested Water (ppt)", x="County")

Top10 %>% 
  filter(COUNTY == "KALAMAZOO") %>% 
  ggplot(aes(x=COUNTY, y=TOTAL_TESTED_PFAS_PPT)) +
  geom_boxplot() +
  labs(title="PFAS Levels in Kalamazoo, Michigan", y="PFAS in Tested Water (ppt)", x="County")

Top10 %>% 
  ggplot(aes(x=reorder(COUNTY, PFAS_YES), fill=PFAS_YES)) +
  geom_bar(position='fill') +
  labs(title="Presence of PFAS Contaminated Water in the Ten Most Tested Michigan Counties", fill="Presence of PFAS in Tested Water", x="County") + 
theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1))  
```

```{r}
Top10 %>%
  filter(TOTAL_TESTED_PFAS_PPT>0) %>% 
  ggplot(aes(x = POPULATION_SERVED, y = TOTAL_TESTED_PFAS_PPT)) +
  geom_point() +
  scale_x_log10(labels = scales::comma_format()) +
  scale_y_log10() +
  labs(title = stringr::str_wrap("Population Drinking PFAS Contaminated Water in Ten Most Tested Michigan Counties", 50), x = "Log of Population Served", y = "Log of PFAS Levels (ppt)")

#Below isn't completely working, and obv need to combine - will correct during class or this evening. Been super busy :(
Top10$TOTAL_TESTED_PFAS_PPT <- as.numeric(Top10$TOTAL_TESTED_PFAS_PPT)

AVERAGE_PFAS <- Top10 %>%
  group_by(COUNTY) %>%
  summarize(AVERAGE_PFAS = mean(TOTAL_TESTED_PFAS_PPT, na.rm = TRUE))

HIGHEST_PFAS <- Top10 %>%
  group_by(COUNTY) %>%
  summarize(HIGHEST_PFAS = max(TOTAL_TESTED_PFAS_PPT, na.rm = TRUE))

AVG_MAX_TABLE <- merge(AVERAGE_PFAS, HIGHEST_PFAS, by = "COUNTY")
print(AVG_MAX_TABLE)

```



```{r}

options(scipen = 100, digits = 4)
small_model <- lm(TOTAL_TESTED_PFAS_PPT ~ POPULATION_SERVED + RAW_OR_TREATED, data=Top10)
main_model <- lm(TOTAL_TESTED_PFAS_PPT ~ -1 + COUNTY + POPULATION_SERVED + RAW_OR_TREATED, data=Top10)
anova(small_model, main_model)

summary(main_model)
confint(main_model, level = 0.95)
```








